import type { DistrictDefinition } from '../model/district-definition';
import { districtConstraints } from './district-constraints';

const centralNodes = Object.freeze([
  Object.freeze({ id: 'north-gate', position: Object.freeze({ x: 0, y: 0, z: -20 }) }),
  Object.freeze({ id: 'civic-square', position: Object.freeze({ x: 0, y: 0, z: -8 }) }),
  Object.freeze({ id: 'market', position: Object.freeze({ x: 12, y: 0, z: -8 }) }),
  Object.freeze({ id: 'hospital', position: Object.freeze({ x: 24, y: 0, z: -8 }) }),
  Object.freeze({ id: 'south-gate', position: Object.freeze({ x: 0, y: 0, z: 10 }) }),
  Object.freeze({ id: 'riverside', position: Object.freeze({ x: 12, y: 0, z: 10 }) }),
  Object.freeze({ id: 'warehouse', position: Object.freeze({ x: 24, y: 0, z: 10 }) }),
  Object.freeze({ id: 'east-hub', position: Object.freeze({ x: 36, y: 0, z: -8 }) }),
]);

const centralEdges = Object.freeze([
  Object.freeze({
    id: 'north-gate-to-civic-square',
    fromNodeId: 'north-gate',
    toNodeId: 'civic-square',
    length: 8,
    capacity: 4,
    isClosable: false,
  }),
  Object.freeze({
    id: 'civic-square-to-market',
    fromNodeId: 'civic-square',
    toNodeId: 'market',
    length: 8,
    capacity: 3,
    isClosable: true,
  }),
  Object.freeze({
    id: 'market-to-hospital',
    fromNodeId: 'market',
    toNodeId: 'hospital',
    length: 8,
    capacity: 3,
    isClosable: false,
  }),
  Object.freeze({
    id: 'hospital-to-east-hub',
    fromNodeId: 'hospital',
    toNodeId: 'east-hub',
    length: 8,
    capacity: 3,
    isClosable: false,
  }),
  Object.freeze({
    id: 'civic-square-to-riverside',
    fromNodeId: 'civic-square',
    toNodeId: 'riverside',
    length: 12,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'riverside-to-warehouse',
    fromNodeId: 'riverside',
    toNodeId: 'warehouse',
    length: 12,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'warehouse-to-east-hub',
    fromNodeId: 'warehouse',
    toNodeId: 'east-hub',
    length: 12,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'south-gate-to-civic-square',
    fromNodeId: 'south-gate',
    toNodeId: 'civic-square',
    length: 10,
    capacity: 3,
    isClosable: false,
  }),
  Object.freeze({
    id: 'civic-square-to-south-gate',
    fromNodeId: 'civic-square',
    toNodeId: 'south-gate',
    length: 10,
    capacity: 3,
    isClosable: false,
  }),
  Object.freeze({
    id: 'south-gate-to-riverside',
    fromNodeId: 'south-gate',
    toNodeId: 'riverside',
    length: 8,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'riverside-to-south-gate',
    fromNodeId: 'riverside',
    toNodeId: 'south-gate',
    length: 8,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'market-to-riverside',
    fromNodeId: 'market',
    toNodeId: 'riverside',
    length: 10,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'riverside-to-market',
    fromNodeId: 'riverside',
    toNodeId: 'market',
    length: 10,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'warehouse-to-hospital',
    fromNodeId: 'warehouse',
    toNodeId: 'hospital',
    length: 8,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'hospital-to-warehouse',
    fromNodeId: 'hospital',
    toNodeId: 'warehouse',
    length: 8,
    capacity: 2,
    isClosable: false,
  }),
  Object.freeze({
    id: 'east-hub-to-hospital',
    fromNodeId: 'east-hub',
    toNodeId: 'hospital',
    length: 8,
    capacity: 3,
    isClosable: false,
  }),
]);

const centralVehicles = Object.freeze([
  Object.freeze({
    id: 'vehicle-01',
    originNodeId: 'north-gate',
    destinationNodeId: 'east-hub',
    spawnTick: 0,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-02',
    originNodeId: 'north-gate',
    destinationNodeId: 'hospital',
    spawnTick: 3,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-03',
    originNodeId: 'south-gate',
    destinationNodeId: 'east-hub',
    spawnTick: 6,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-04',
    originNodeId: 'civic-square',
    destinationNodeId: 'east-hub',
    spawnTick: 9,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-05',
    originNodeId: 'market',
    destinationNodeId: 'east-hub',
    spawnTick: 12,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-06',
    originNodeId: 'riverside',
    destinationNodeId: 'east-hub',
    spawnTick: 15,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-07',
    originNodeId: 'south-gate',
    destinationNodeId: 'hospital',
    spawnTick: 18,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-08',
    originNodeId: 'civic-square',
    destinationNodeId: 'hospital',
    spawnTick: 21,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-09',
    originNodeId: 'north-gate',
    destinationNodeId: 'market',
    spawnTick: 24,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
  Object.freeze({
    id: 'vehicle-10',
    originNodeId: 'south-gate',
    destinationNodeId: 'market',
    spawnTick: 27,
    baseSpeed: districtConstraints.baseVehicleSpeed,
  }),
]);

export const centralDistrictDefinition = Object.freeze({
  id: 'central-district',
  nodes: centralNodes,
  edges: centralEdges,
  display: Object.freeze({
    label: 'Central District',
    areas: Object.freeze([
      Object.freeze({
        id: 'civic-core',
        label: 'Civic Core',
        position: Object.freeze({ x: 6, y: 0, z: -3 }),
      }),
      Object.freeze({
        id: 'riverside-quarter',
        label: 'Riverside Quarter',
        position: Object.freeze({ x: 18, y: 0, z: 4 }),
      }),
    ]),
  }),
  baselineVehicles: centralVehicles,
  emergencyAccessProbe: Object.freeze({
    id: 'emergency-access',
    originNodeId: 'north-gate',
    destinationNodeId: 'hospital',
  }),
  deliveryAccessProbe: Object.freeze({
    id: 'delivery-access',
    originNodeId: 'south-gate',
    destinationNodeId: 'east-hub',
  }),
} satisfies DistrictDefinition);
